language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database maintenance;' -U postgres
  - psql -c 'create database maintenance_test;' -U postgres
  - psql -c "create user janet with password '123456'; " -U postgres

script:
  - python -m pytest --cov-report term-missing --cov=views

after_success:
  - coveralls

